# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               YeshG's Technical Blog
tagline:             'A Technical Blog'
description:         'A collection of personal notes and articles by <a href="https://www.github.com/yeshg" target="_blank">yeshg</a>.'
url:                 http://yeshg.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yesh Godse
  url:               https://www.github.com/yeshg
  email:             yesh.godse@gmail.com

# Custom vars
version:             1.0.0
excerpt_separator: "\n\n"
